/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_kine_login (void);
GtkWidget* create_Espace_kine (void);
GtkWidget* create_Rendez_vous (void);
GtkWidget* create_fiche (void);
